/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ผู้ใช้ที่ล็อกอินอยู่ */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ออกจากระบบ (ยกเลิก token ปัจจุบัน) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายชื่อผู้ใช้ (ใช้ในตัวกรอง) */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** บทบาทและสิทธิ์ทั้งหมด */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เกณฑ์การอนุมัติ */
        get: operations["getApprovalSettings"];
        /** แก้ไขเกณฑ์การอนุมัติ (แอดมิน/เจ้าของบริษัท) */
        put: operations["updateApprovalSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการโครงการที่ผู้ใช้มีสิทธิ์เห็น */
        get: operations["listProjects"];
        put?: never;
        /**
         * เปิดโครงการใหม่ (ต้องมีสิทธิ์ project.create)
         * @description หลังบ้านออกรหัสโครงการ (รหัสภูมิภาค + ปี พ.ศ. 2 หลัก + ลำดับ 4 หลัก เช่น CR690003) และบันทึก Audit Log
         *     โครงการใหม่มีสถานะ pending-contract (ยังไม่มีมูลค่า วันที่ และแผนงาน จนกว่าจะบันทึกสัญญาและตั้งค่างานก่อสร้าง)
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/project-regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รหัสภูมิภาคที่ใช้ขึ้นต้นรหัสโครงการ */
        get: operations["listProjectRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/construction-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ตัวเลือกในหน้าตั้งค่างานก่อสร้าง (ประเภทอาคาร ฐานราก ระบบพิเศษ ฯลฯ)
         * @description หน้าบ้านสร้างฟอร์มจากรายการนี้ทั้งหมด เพิ่มตัวเลือกใหม่ที่หลังบ้านได้โดยไม่ต้องแก้หน้าบ้าน
         *     งานที่ต้องทำของแต่ละตัวเลือกกำหนดที่หลังบ้าน (แม่แบบแผนงาน)
         */
        get: operations["listConstructionOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/house-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** แบบบ้านทั้งหมดที่เลือกได้ตอนเปิดโครงการ */
        get: operations["listHousePlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/contract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * บันทึกสัญญาและเริ่มแผนงาน (ต้องมีสิทธิ์ project.manage)
         * @description ใช้กับโครงการสถานะ pending-contract เท่านั้น
         *     หลังบ้านบันทึกมูลค่า/วันที่ สร้างแผนงานจากแม่แบบให้พอดีกับวันเริ่ม-วันส่งมอบ สร้างงวดงาน เปลี่ยนสถานะเป็น planning และบันทึก Audit Log
         *     ไทม์ไลน์ยังไม่ถูกสร้างจนกว่าจะตั้งค่างานก่อสร้าง (PUT /projects/{code}/setup)
         *     endpoint ข้อมูลรายโครงการ (timeline, installments, photos, documents, team, updates, inspection) ตอบ 409 จนกว่าจะบันทึกสัญญาและตั้งค่างานก่อสร้าง
         */
        post: operations["recordProjectContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /**
         * การตั้งค่างานก่อสร้างของโครงการ
         * @description ยังไม่ตั้งค่า → configured = false และ options เป็นค่าเริ่มต้น; 409 ถ้ายังไม่บันทึกสัญญา
         */
        get: operations["getProjectSetup"];
        /**
         * บันทึกการตั้งค่างานก่อสร้างและสร้างไทม์ไลน์ (ต้องมีสิทธิ์ project.manage)
         * @description หลังบ้านคัดงานจากแม่แบบตามตัวเลือก จัดวันที่ให้พอดีกับระยะสัญญา สร้างไทม์ไลน์และงวดงานใหม่ และบันทึก Audit Log
         *     ตัวเลือกที่ถูกซ่อน (visibleWhen ไม่ตรง) หลังบ้านปรับเป็นค่าเริ่มต้นเอง
         *     409 ถ้ายังไม่บันทึกสัญญา หรือเริ่มรายงานความคืบหน้าแล้ว (locked)
         */
        put: operations["saveProjectSetup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/setup/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ดูตัวอย่างงานที่จะเกิดขึ้นจากตัวเลือก (ไม่บันทึก) */
        post: operations["previewProjectSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /** ไทม์ไลน์ตามแผนงานพร้อมความคืบหน้ารายงาน */
        get: operations["getProjectTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /** บันทึกหน้างาน/ประวัติการอัปเดตความคืบหน้า (ล่าสุดก่อน) */
        get: operations["listProgressUpdates"];
        put?: never;
        /**
         * บันทึกความคืบหน้าประจำวัน
         * @description หลังบ้านปรับ % ของงานที่ระบุ แล้วคำนวณ % ของขั้นตอนและภาพรวมโครงการใหม่ (ถ่วงน้ำหนักตามจำนวนวันของงาน)
         *     หมุดหมาย (milestone) เสร็จอัตโนมัติเมื่องานอื่นในขั้นตอนเสร็จครบ
         *     งานที่เป็นจุดตรวจ (Hold Point) อัปเดตผ่าน endpoint นี้ไม่ได้ ต้องใช้ /inspection
         *     การลด % ต้องระบุเหตุผลใน note
         */
        post: operations["createProgressUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/tasks/{taskCode}/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                taskCode: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** บันทึกผลตรวจจุด Hold Point (ผ่าน = งานเสร็จ, ไม่ผ่าน = ต้องแก้ไขและตรวจใหม่) */
        post: operations["recordInspection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** อัปโหลดไฟล์ (รูปหน้างาน) แล้วนำ id ไปอ้างอิงในบันทึก */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/installments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /** งวดงานและการชำระเงินของลูกค้า */
        get: operations["listProjectInstallments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /** ภาพถ่ายหน้างาน (ล่าสุดก่อน) */
        get: operations["listProjectPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get: operations["listProjectDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /**
         * ผู้รับผิดชอบ (บุคลากร) และผู้รับเหมาช่วงของโครงการ
         * @description ความคืบหน้า/สถานะของผู้รับเหมาช่วง หลังบ้านคำนวณจากขั้นตอนที่มอบหมายในไทม์ไลน์; contractValue ส่งเฉพาะผู้มีสิทธิ์ project.manage
         */
        get: operations["getProjectAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * มอบหมายบุคลากรเป็นผู้รับผิดชอบในโครงการ (ต้องมีสิทธิ์ project.manage)
         * @description ผู้จัดการโครงการคนแรกในรายการคือ responsibleName ของโครงการ (หลังบ้านอัปเดตให้); คนเดิมซ้ำในบทบาทเดิมตอบ 409
         */
        post: operations["addProjectStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/staff/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** แก้บทบาท/หมายเหตุของผู้รับผิดชอบ */
        put: operations["updateProjectStaff"];
        post?: never;
        /** นำผู้รับผิดชอบออกจากโครงการ — โครงการต้องมีผู้จัดการโครงการอย่างน้อย 1 คน (409) */
        delete: operations["removeProjectStaff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/subcontractors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * มอบหมายผู้รับเหมาช่วงตามขั้นตอนงาน (ต้องมีสิทธิ์ project.manage)
         * @description ต้องตั้งค่างานก่อสร้างแล้ว (ใช้ขั้นตอนจากไทม์ไลน์); ผู้รับเหมาที่ปิดใช้งานมอบหมายไม่ได้ (422); ผู้รับเหมารายเดิมซ้ำในโครงการเดียวกันตอบ 409 (ให้แก้ไขรายการเดิม)
         */
        post: operations["addProjectSubcontractor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/subcontractors/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** แก้ขอบเขตงาน ขั้นตอน มูลค่าจ้าง */
        put: operations["updateProjectSubcontractor"];
        post?: never;
        /** ยกเลิกการมอบหมาย — ลบไม่ได้เมื่อขั้นตอนที่รับผิดชอบเริ่มงานแล้ว (409) ให้แก้ไขแทน */
        delete: operations["removeProjectSubcontractor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subcontractors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ทะเบียนผู้รับเหมาช่วง */
        get: operations["listSubcontractors"];
        put?: never;
        /** เพิ่มผู้รับเหมาช่วง (ต้องมีสิทธิ์ project.manage) — หลังบ้านออกรหัส SUB-xxx */
        post: operations["createSubcontractor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subcontractors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** แก้ไขข้อมูลผู้รับเหมาช่วง / เปิด-ปิดใช้งาน */
        put: operations["updateSubcontractor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{code}/team": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        /** รายชื่อติดต่อทีมงานโครงการ (สร้างจากผู้รับผิดชอบที่มอบหมายใน /assignments) */
        get: operations["listProjectTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/house-plans/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        /** แบบบ้าน แปลนรายชั้น และไฟล์โมเดล 3D */
        get: operations["getHousePlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPersonnel"];
        put?: never;
        /** เพิ่มบุคลากร (หลังบ้านออกรหัสบุคลากร) */
        post: operations["createPersonnel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getPersonnel"];
        put: operations["updatePersonnel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/license-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ใบอนุญาต/เอกสารที่หมดอายุหรือใกล้หมดอายุ */
        get: operations["listLicenseAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** คำขออนุมัติที่ผู้ใช้มีสิทธิ์เห็น (ล่าสุดก่อน) */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตัวเลขสรุป (ใช้กับแถบแจ้งเตือนและการ์ดสรุป) */
        get: operations["getApprovalSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rejectApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/bulk-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** อนุมัติหลายรายการ (รายการที่ทำไม่ได้จะอยู่ใน skipped) */
        post: operations["bulkApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** บันทึกการกระทำ (ล่าสุดก่อน, อ่านอย่างเดียว) */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ส่งออก CSV ตามตัวกรองเดียวกับ /audit-logs (UTF-8 พร้อม BOM) */
        get: operations["exportAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** กำไร-ขาดทุนรายโครงการและยอดรวมบริษัท (เจ้าของบริษัท) */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * จำนวนโครงการตามสถานะ (ในมือ เสร็จแล้ว กำลังดำเนินการ รอทำสัญญา อยู่ในประกัน)
         * @description inHandValue ส่งเฉพาะผู้มีสิทธิ์ finance.company
         */
        get: operations["getProjectPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/cash-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เงินรับ-เงินจ่ายรายเดือน (เดือนล่าสุดนับถึงวันนี้) */
        get: operations["getCashFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            /** @description ข้อความสั้นสำหรับแสดงผู้ใช้ (ภาษาไทย) */
            title: string;
            status: number;
            detail?: string;
            /** @description ข้อผิดพลาดรายช่อง (ชื่อช่อง → ข้อความ) */
            errors?: {
                [key: string]: string;
            };
        };
        PageMeta: {
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        RoleId: "admin" | "owner" | "admin-staff" | "accounting" | "procurement" | "storekeeper" | "auditor" | "project-manager" | "engineer" | "architect" | "foreman" | "safety-officer" | "subcontractor" | "client" | "supplier";
        UserRef: {
            id: string;
            name: string;
            /** @description ชื่อบทบาท ณ เวลาที่เกิดเหตุการณ์ */
            roleLabel: string;
        };
        /**
         * @description สิทธิ์ที่หน้าบ้านใช้ตัดสินว่าจะแสดงปุ่ม/ส่วนใด (หลังบ้านต้องตรวจสิทธิ์ซ้ำทุกคำขอ)
         *     - progress.update: บันทึกความคืบหน้าและผลตรวจ
         *     - personnel.sensitive: ดู/แก้ข้อมูลอ่อนไหวของบุคลากร
         *     - finance.company: ดูการเงินระดับบริษัท (Dashboard กำไร-ขาดทุน)
         *     - approval.any: อนุมัติได้ทุกยอด
         *     - project.create: เปิดโครงการใหม่
         *     - project.manage: จัดการโครงการ เช่น บันทึกสัญญาและเริ่มแผนงาน
         * @enum {string}
         */
        Permission: "progress.update" | "personnel.sensitive" | "finance.company" | "approval.any" | "project.create" | "project.manage";
        CurrentUser: {
            id: string;
            name: string;
            roleId: components["schemas"]["RoleId"];
            roleLabel: string;
            /** @description โครงการที่เป็นสมาชิก (ว่าง = ทุกโครงการสำหรับทีมภายใน) */
            projectCodes: string[];
            /** Format: email */
            email: string;
            phone?: string;
            /** @description ตำแหน่งงาน */
            position?: string;
            department?: string;
            /** @description รหัสบุคลากร (ไม่มีสำหรับบุคคลภายนอก) */
            employeeCode?: string;
            /** Format: uri */
            avatarUrl?: string;
            /**
             * Format: date-time
             * @description เวลาเข้าสู่ระบบครั้งก่อนหน้า
             */
            lastLoginAt: string;
            permissions: components["schemas"]["Permission"][];
        };
        RoleCatalog: {
            groups: {
                /** @enum {string} */
                id: "internal" | "project" | "external";
                label: string;
                scope: string;
            }[];
            roles: {
                id: components["schemas"]["RoleId"];
                /** @enum {string} */
                group: "internal" | "project" | "external";
                label: string;
                access: string;
                restriction: string;
                suggested?: boolean;
                optional?: boolean;
            }[];
        };
        ApprovalSettings: {
            /** @description วงเงินที่ผู้จัดการโครงการอนุมัติได้ต่อรายการ (บาท) */
            projectManagerLimit: number;
            /** @description งานเพิ่ม-ลดต้องให้เจ้าของอนุมัติทุกยอด */
            changeOrderRequiresOwner: boolean;
        };
        ProjectRegion: {
            /**
             * @description รหัสขึ้นต้นโครงการ
             * @example CR
             */
            code: string;
            /** @example เชียงราย */
            province: string;
        };
        /** @description ข้อมูลเบื้องต้นตอนเปิดโครงการ (ก่อนเซ็นสัญญา) — มูลค่าและวันที่บันทึกภายหลังที่ POST /projects/{code}/contract */
        ProjectInput: {
            /** @description ชื่อโครงการ (ผู้ใช้ตั้งเอง) */
            name: string;
            /** @description จังหวัดที่ตั้งโครงการ ใช้ออกรหัส (GET /settings/project-regions) */
            regionCode: string;
            customerName: string;
            /** @description เบอร์โทรลูกค้า 9-10 หลัก */
            phone: string;
            customerEmail?: string;
            customerLineId?: string;
            /** @description ที่อยู่ติดต่อลูกค้า */
            customerAddress?: string;
            /** @description ผู้รับผิดชอบโครงการ */
            responsibleName: string;
            /** @description แบบบ้านที่ลูกค้าต้องการ (พิมพ์เองได้) */
            housePlanName: string;
            /** @description ถ้าเลือกจากคลังแบบบ้าน (GET /house-plans) จะแสดงแปลนและโมเดล 3D ได้ */
            housePlanCode?: string;
            /** @description ความต้องการเพิ่มเติมของลูกค้า */
            requirements?: string;
        };
        /** @description บันทึกเมื่อได้งาน/เซ็นสัญญาแล้ว หลังบ้านจะสร้างแผนงานจากแม่แบบและงวดงาน */
        ContractInput: {
            /** @description มูลค่าสัญญา (บาท) */
            value: number;
            /**
             * Format: date
             * @description วันที่เซ็นสัญญา (ไม่เกินวันนี้)
             */
            signedDate: string;
            /**
             * Format: date
             * @description วันเริ่มงาน (ไม่ก่อนวันเซ็นสัญญา)
             */
            startDate: string;
            /**
             * Format: date
             * @description ต้องห่างจากวันเริ่มอย่างน้อย 30 วัน
             */
            deliveryDate: string;
            /** @description ที่ตั้งหน้างาน (เลขที่/ตำบล/อำเภอ) */
            location: string;
        };
        /**
         * @description pending-contract = เปิดโครงการแล้วแต่ยังไม่ได้บันทึกสัญญา (ยังไม่มีแผนงาน งวดงาน ภาพ เอกสาร)
         * @enum {string}
         */
        ProjectStatus: "pending-contract" | "planning" | "in-progress" | "near-handover" | "completed" | "delayed";
        Project: {
            /** @example CR690001 */
            code: string;
            name: string;
            /** @description ที่ตั้งหน้างาน (null จนกว่าจะบันทึกสัญญา) */
            location: string | null;
            housePlanName: string;
            housePlanCode?: string;
            requirements?: string;
            customerName: string;
            phone: string;
            customerEmail?: string;
            customerLineId?: string;
            customerAddress?: string;
            responsibleName: string;
            /** @description มูลค่าสัญญา (null จนกว่าจะบันทึกสัญญา) */
            value: number | null;
            /** Format: date */
            startDate: string | null;
            /** Format: date */
            deliveryDate: string | null;
            /** Format: date */
            contractSignedAt: string | null;
            progress: number;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Format: date-time
             * @description วันที่เปิดโครงการ
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description เวลาที่ตั้งค่างานก่อสร้าง (null = ยังไม่ตั้งค่า ยังไม่มีไทม์ไลน์)
             */
            setupConfiguredAt?: string | null;
            /**
             * Format: date
             * @description วันที่ส่งมอบงานจริง (null = ยังไม่ส่งมอบ)
             */
            handedOverAt?: string | null;
            /**
             * Format: date
             * @description วันสิ้นสุดการรับประกันผลงาน (หลังบ้านคำนวณจากวันส่งมอบ + ระยะประกัน)
             */
            warrantyUntil?: string | null;
        };
        /** @description single = รหัสตัวเลือก, multiple = รายการรหัส, boolean = true/false */
        ConstructionOptionValue: string | boolean | string[];
        ConstructionOptionChoice: {
            value: string;
            label: string;
            description?: string;
        };
        ConstructionOptionGroup: {
            /** @example foundation */
            key: string;
            /** @description หัวข้อที่ใช้จัดกลุ่มในฟอร์ม เช่น งานฐานราก */
            section: string;
            label: string;
            description?: string;
            /** @enum {string} */
            type: "single" | "multiple" | "boolean";
            /** @description ว่างเมื่อ type = boolean */
            choices: components["schemas"]["ConstructionOptionChoice"][];
            default: components["schemas"]["ConstructionOptionValue"];
            /** @description ขั้นตอนในแผนงานที่ตัวเลือกนี้เพิ่ม/เปลี่ยนงาน (หลังบ้านคำนวณจากแม่แบบ) */
            affectsPhases: {
                code: string;
                shortName: string;
            }[];
            /** @description แสดงเฉพาะเมื่อตัวเลือก key มีค่าอยู่ใน values */
            visibleWhen?: {
                key: string;
                values: string[];
            };
        };
        /** @description ค่าของแต่ละตัวเลือก (key → ค่า) ตาม GET /settings/construction-options */
        ConstructionSetupOptions: {
            [key: string]: components["schemas"]["ConstructionOptionValue"];
        };
        /** @description งานย่อยที่เพิ่มเองในโครงการนี้ (นอกแม่แบบ) */
        CustomTaskInput: {
            /** @description รหัสที่หน้าบ้านสร้าง ใช้อ้างอิงตอนแก้ไข/ลบ */
            id: string;
            /** @example 05 */
            phaseCode: string;
            name: string;
            /** @description ไม่ระบุ = ผู้รับเหมา */
            team?: string;
            /** @description ทำต่อจากงานรหัสนี้ในขั้นตอนเดียวกัน (ไม่ระบุ = ต่อท้ายงานสุดท้ายของขั้นตอน) */
            afterCode?: string;
            durationDays: number;
            /**
             * @description เป็นจุดตรวจที่ต้องผ่านก่อนทำงานถัดไป
             * @default false
             */
            isHoldPoint: boolean;
        };
        ProjectSetupInput: {
            options: components["schemas"]["ConstructionSetupOptions"];
            /** @description รหัสงานย่อยที่ไม่ต้องทำในโครงการนี้ — ตัดจุดตรวจ (Hold Point) และหมุดหมาย (Milestone) ไม่ได้ (422); รหัสที่ไม่อยู่ในแผนตามตัวเลือก หลังบ้านตัดทิ้ง */
            excludedTasks?: string[];
            customTasks?: components["schemas"]["CustomTaskInput"][];
        };
        ProjectSetup: {
            configured: boolean;
            /** @description true เมื่อเริ่มรายงานความคืบหน้าแล้ว แก้การตั้งค่าไม่ได้ */
            locked: boolean;
            lockedReason?: string;
            /** Format: date-time */
            configuredAt: string | null;
            configuredBy: string | null;
            options: components["schemas"]["ConstructionSetupOptions"];
            excludedTasks: string[];
            customTasks: components["schemas"]["CustomTaskInput"][];
        };
        /** @description งานย่อยในแผน รวมงานที่ถูกตัดออก (included = false) เพื่อให้เลือกกลับได้ */
        SetupPreviewTask: {
            code: string;
            name: string;
            team: string;
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
            isHoldPoint: boolean;
            isMilestone: boolean;
            /** @description งานที่มีเพราะตัวเลือกที่เลือก (ไม่ใช่งานพื้นฐาน) */
            optional: boolean;
            /** @description false = ตัดออกจากโครงการนี้ (ไม่อยู่ในไทม์ไลน์) */
            included: boolean;
            /** @description จุดตรวจ/หมุดหมาย ตัดออกไม่ได้ */
            required: boolean;
            /** @description งานที่เพิ่มเอง */
            custom: boolean;
            /** @description id ของ CustomTaskInput (เฉพาะงานที่เพิ่มเอง) */
            customId?: string;
        };
        SetupPreview: {
            /** @description งานที่ทำจริง (ไม่รวมหมุดหมายและงานที่ตัดออก) */
            taskCount: number;
            excludedCount: number;
            customCount: number;
            holdPointCount: number;
            milestoneCount: number;
            optionalTaskCount: number;
            phases: {
                step: number;
                code: string;
                name: string;
                shortName: string;
                /** Format: date */
                start: string;
                /** Format: date */
                end: string;
                tasks: components["schemas"]["SetupPreviewTask"][];
            }[];
        };
        /** @enum {string} */
        TimelineStatus: "done" | "active" | "pending";
        TimelineTask: {
            code: string;
            name: string;
            team: string;
            note?: string;
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
            progress: number;
            status: components["schemas"]["TimelineStatus"];
            isHoldPoint: boolean;
            isMilestone: boolean;
            isPaymentMilestone: boolean;
            involvesOwner: boolean;
        };
        TimelinePhase: {
            step: number;
            code: string;
            name: string;
            shortName: string;
            summary: string;
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
            progress: number;
            status: components["schemas"]["TimelineStatus"];
            tasks: components["schemas"]["TimelineTask"][];
            holdPoints: {
                passed: number;
                total: number;
            };
        };
        ProjectTimeline: {
            progress: number;
            phases: components["schemas"]["TimelinePhase"][];
        };
        UploadedFile: {
            id: string;
            /** Format: uri */
            url: string;
            name: string;
            sizeKb: number;
            contentType: string;
        };
        /** @enum {string} */
        Weather: "sunny" | "cloudy" | "light-rain" | "heavy-rain";
        /** @enum {string} */
        IssueSeverity: "low" | "medium" | "high";
        SiteIssue: {
            title: string;
            severity: components["schemas"]["IssueSeverity"];
        };
        TaskProgressInput: {
            taskCode: string;
            progress: number;
        };
        /** @description ต้องมีอย่างน้อย 1 อย่าง ได้แก่ taskChanges, note หรือ documents */
        ProgressUpdateInput: {
            /**
             * Format: date
             * @description วันที่ทำงาน (ไม่เกินวันนี้)
             */
            reportDate: string;
            weather: components["schemas"]["Weather"];
            /** @description จำนวนแรงงานในวันนั้น */
            workers: number;
            note?: string;
            taskChanges?: components["schemas"]["TaskProgressInput"][];
            issues?: components["schemas"]["SiteIssue"][];
            /** @description id จาก POST /uploads (ต้องเป็นไฟล์รูป) */
            photoIds?: string[];
            /** @description เอกสารแนบ จะถูกเพิ่มในเอกสารของโครงการ (GET /projects/{code}/documents) */
            documents?: components["schemas"]["DocumentAttachmentInput"][];
        };
        DocumentAttachmentInput: {
            /** @description id จาก POST /uploads */
            fileId: string;
            category: components["schemas"]["DocumentCategory"];
            /** @description ชื่อเอกสาร (ไม่ระบุ = ใช้ชื่อไฟล์) */
            name?: string;
        };
        InspectionInput: {
            /** @enum {string} */
            result: "passed" | "failed";
            /** @description จำเป็นเมื่อไม่ผ่าน */
            note?: string;
            photoIds?: string[];
            /** @description เช่น รายงานผลตรวจ ผลทดสอบ */
            documents?: components["schemas"]["DocumentAttachmentInput"][];
        };
        ProgressUpdate: {
            id: string;
            projectCode: string;
            /** Format: date */
            reportDate: string;
            /** Format: date-time */
            createdAt: string;
            author: components["schemas"]["UserRef"];
            weather: components["schemas"]["Weather"];
            workers: number;
            note?: string;
            taskChanges: {
                taskCode: string;
                taskName: string;
                phaseStep: number;
                from: number;
                to: number;
            }[];
            inspection?: {
                taskCode: string;
                taskName: string;
                /** @enum {string} */
                result: "passed" | "failed";
            };
            issues: components["schemas"]["SiteIssue"][];
            photos: components["schemas"]["UploadedFile"][];
            /** @description เอกสารที่แนบกับบันทึกนี้ */
            documents: components["schemas"]["ProjectDocument"][];
            /** @description % ภาพรวมโครงการหลังบันทึกนี้ */
            overallProgress: number;
        };
        ProgressUpdatePage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["ProgressUpdate"][];
        };
        /** @enum {string} */
        InstallmentStatus: "paid" | "due" | "working" | "upcoming";
        Installment: {
            no: number;
            title: string;
            phaseSteps: number[];
            percent: number;
            amount: number;
            status: components["schemas"]["InstallmentStatus"];
            /** Format: date */
            dueDate: string;
            /** Format: date */
            paidDate?: string | null;
        };
        SitePhoto: {
            id: string;
            /** Format: uri */
            url: string;
            /** Format: uri */
            thumbnailUrl: string;
            /** Format: date-time */
            takenAt: string;
            caption: string;
            phaseCode: string;
            phaseStep: number;
            phaseShortName: string;
        };
        SitePhotoPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["SitePhoto"][];
            /** @description จำนวนภาพแยกตามขั้นตอน (ไม่ขึ้นกับตัวกรอง phaseCode) ใช้ทำตัวกรอง */
            phases: {
                phaseCode: string;
                phaseStep: number;
                phaseShortName: string;
                count: number;
            }[];
        };
        /** @enum {string} */
        DocumentCategory: "contract" | "drawing" | "permit" | "inspection" | "billing" | "handover";
        ProjectDocument: {
            id: string;
            category: components["schemas"]["DocumentCategory"];
            name: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            fileType: "pdf" | "dwg" | "xlsx" | "docx" | "image";
            sizeKb: number;
            /**
             * Format: uri
             * @description ลิงก์ชั่วคราว (signed URL)
             */
            downloadUrl: string;
            /** @description ผู้แนบเอกสาร (เอกสารที่ระบบสร้างเองไม่มีฟิลด์นี้) */
            uploadedBy?: string;
            /** @description บันทึกหน้างานที่แนบเอกสารนี้ (ถ้ามี) */
            updateId?: string;
        };
        /**
         * @description สาขางานของผู้รับเหมาช่วง (หน้าบ้านแปลเป็นข้อความไทย)
         * @enum {string}
         */
        SubcontractorTrade: "piling" | "structure" | "masonry" | "roofing" | "waterproofing" | "electrical" | "plumbing" | "hvac" | "aluminium" | "tiling" | "ceiling" | "painting" | "carpentry" | "landscape" | "solar" | "pool" | "lift" | "fire" | "other";
        SubcontractorInput: {
            /** @description ชื่อบริษัท/ทีมช่าง */
            name: string;
            trades: components["schemas"]["SubcontractorTrade"][];
            contactName: string;
            /** @description ตัวเลข 9-10 หลัก ขึ้นต้นด้วย 0 */
            phone: string;
            email?: string;
            lineId?: string;
            /** @description เลขประจำตัวผู้เสียภาษี 13 หลัก (ซ้ำกับรายอื่นไม่ได้ 409) */
            taxId?: string;
            address?: string;
            note?: string;
            /**
             * @description inactive = ไม่ใช้งานแล้ว มอบหมายงานใหม่ไม่ได้
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        Subcontractor: components["schemas"]["SubcontractorInput"] & {
            id: string;
            /** @example SUB-001 */
            code: string;
            /** @description จำนวนโครงการที่ยังไม่ส่งมอบที่มอบหมายอยู่ */
            activeProjects: number;
        };
        /** @enum {string} */
        StaffRole: "project-manager" | "engineer" | "site-supervisor" | "architect" | "foreman" | "safety-officer" | "purchasing" | "accounting";
        StaffAssignmentInput: {
            personnelId: string;
            role: components["schemas"]["StaffRole"];
            /** @description เช่น หน้าที่เฉพาะในโครงการนี้ */
            note?: string;
        };
        StaffAssignment: {
            id: string;
            personnelId: string;
            name: string;
            position?: string;
            phone?: string;
            role: components["schemas"]["StaffRole"];
            note?: string;
        };
        SubcontractorAssignmentInput: {
            subcontractorId: string;
            /** @description ขอบเขตงานที่จ้าง */
            scope: string;
            /** @description ขั้นตอนในไทม์ไลน์ที่รับผิดชอบ */
            phaseCodes: string[];
            /** @description มูลค่าจ้าง (บาท) */
            contractValue?: number;
            note?: string;
        };
        SubcontractorAssignment: {
            id: string;
            subcontractor: {
                id: string;
                code: string;
                name: string;
                contactName: string;
                phone: string;
                trades: components["schemas"]["SubcontractorTrade"][];
            };
            scope: string;
            phaseCodes: string[];
            /** @description ส่งเฉพาะผู้มีสิทธิ์ project.manage */
            contractValue?: number;
            note?: string;
            /**
             * Format: date
             * @description วันเริ่มของขั้นตอนแรกที่รับผิดชอบ
             */
            start: string;
            /** Format: date */
            end: string;
            /** @description ความคืบหน้าของขั้นตอนที่รับผิดชอบ (ถ่วงตามระยะเวลา) */
            progress: number;
            /** @enum {string} */
            status: "upcoming" | "working" | "done";
        };
        ProjectAssignments: {
            staff: components["schemas"]["StaffAssignment"][];
            subcontractors: components["schemas"]["SubcontractorAssignment"][];
        };
        TeamMember: {
            name: string;
            role: string;
            phone: string;
        };
        /** @enum {string} */
        RoomKind: "bedroom" | "bathroom" | "living" | "dining" | "kitchen" | "garage" | "stair" | "void" | "other";
        HousePlan: {
            code: string;
            name: string;
            description: string;
            /** @description เมตร */
            width: number;
            /** @description เมตร */
            depth: number;
            floorHeight: number;
            parking: number;
            /**
             * Format: uri
             * @description ภาพทัศนียภาพ
             */
            renderUrl?: string;
            /**
             * Format: uri
             * @description ไฟล์โมเดล .glb
             */
            modelUrl?: string;
            floors: {
                label: string;
                rooms: {
                    name: string;
                    kind: components["schemas"]["RoomKind"];
                    x: number;
                    y: number;
                    w: number;
                    h: number;
                }[];
            }[];
        };
        PersonnelDocument: {
            /** @description ประเภทเอกสาร เช่น สำเนาบัตรประชาชน */
            type: string;
            fileName: string;
            /**
             * Format: uri
             * @description ลิงก์จาก POST /uploads
             */
            url: string;
            /** Format: date */
            expiresAt?: string;
            /** @description หลังบ้านใส่ให้ (ไม่ต้องส่ง) */
            uploadedBy?: string;
        };
        PersonnelTraining: {
            name: string;
            /** Format: date */
            completedAt: string;
            /** Format: date */
            expiresAt?: string;
        };
        /** @description ข้อมูลอ่อนไหว ส่งมาเฉพาะบทบาทที่มีสิทธิ์ (เจ้าของบริษัท บัญชี/การเงิน) บทบาทอื่นไม่มีฟิลด์นี้ และค่าที่ส่งเข้ามาจะถูกละเว้น */
        PersonnelSensitive: {
            /** @description เงินเดือน / รายวัน / เหมางาน */
            compensationType?: string;
            compensationRate?: number;
            compensationHistory?: string;
            withholdingTaxTerms?: string;
            bankName?: string;
            bankAccountNumber?: string;
            bankAccountName?: string;
            taxpayerId?: string;
            withholdingCertificate?: string;
            performanceRating?: string;
            performanceNotes?: string;
        };
        /** @description ข้อมูลที่แก้ไขได้ในหน้าบุคลากร (วันที่ว่างให้ละฟิลด์ไว้) */
        PersonnelInput: {
            /** @description ลิงก์จาก POST /uploads */
            photoUrl?: string;
            fullName: string;
            nationalId?: string;
            position?: string;
            /** Format: date */
            birthDate?: string;
            /** Format: date */
            hireDate?: string;
            /** Format: date */
            endDate?: string;
            phone?: string;
            lineId?: string;
            email?: string;
            registeredAddress?: string;
            currentAddress?: string;
            emergencyContactName?: string;
            emergencyContactRelation?: string;
            emergencyContactPhone?: string;
            /** @description ประจำ / รายเดือน / รายวัน */
            employmentType?: string;
            department?: string;
            supervisor?: string;
            expertise?: string;
            workAreas?: string;
            availability?: string;
            education?: string;
            institution?: string;
            otherCertificates?: string;
            professionalLicenseNumber?: string;
            professionalLicenseType?: string;
            professionalLicenseLevel?: string;
            /** Format: date */
            professionalLicenseExpiresAt?: string;
            /** Format: date */
            workPermitExpiresAt?: string;
            socialSecurityNumber?: string;
            issuedEquipment?: string;
            documents?: components["schemas"]["PersonnelDocument"][];
            trainings?: components["schemas"]["PersonnelTraining"][];
            sensitive?: components["schemas"]["PersonnelSensitive"];
        };
        Personnel: components["schemas"]["PersonnelInput"] & {
            id: string;
            /**
             * @description หลังบ้านออกให้เมื่อเพิ่มบุคลากร
             * @example EMP690001
             */
            employeeCode: string;
            /** @description หลังบ้านสร้างจากการมอบหมายงาน (อ่านอย่างเดียว) */
            projectHistory: {
                projectCode: string;
                role: string;
                period: string;
                assignment: string;
                dailyReport: string;
                /** @description ส่งมาเฉพาะบทบาทที่เห็นข้อมูลอ่อนไหว */
                paidAmount?: number;
            }[];
            /** @description ประวัติการแก้ไข (อ่านอย่างเดียว) */
            auditHistory: {
                /** Format: date-time */
                at: string;
                userName: string;
                action: string;
            }[];
        };
        LicenseAlert: {
            personnelId: string;
            fullName: string;
            license: string;
            /** Format: date */
            expiresAt: string;
            expired: boolean;
        };
        /** @enum {string} */
        ApprovalType: "pr" | "po" | "subcontract" | "change-order" | "petty-cash" | "rental";
        /** @enum {string} */
        ApprovalStatus: "pending" | "approved" | "rejected";
        /**
         * @description ผู้มีอำนาจอนุมัติตามเกณฑ์ (หลังบ้านคำนวณจากยอดและประเภท)
         * @enum {string}
         */
        ApprovalLevel: "project-manager" | "owner";
        ApprovalItem: {
            name: string;
            quantity: number;
            unit: string;
            unitPrice: number;
        };
        ApprovalStep: {
            /** @enum {string} */
            action: "submitted" | "approved" | "rejected";
            user: components["schemas"]["UserRef"];
            /** Format: date-time */
            at: string;
            note?: string;
        };
        Approval: {
            id: string;
            type: components["schemas"]["ApprovalType"];
            projectCode: string;
            title: string;
            reason?: string;
            /** @description ยอดรวม = ผลรวม quantity × unitPrice */
            amount: number;
            requestedBy: components["schemas"]["UserRef"];
            /** Format: date-time */
            requestedAt: string;
            status: components["schemas"]["ApprovalStatus"];
            approvalLevel: components["schemas"]["ApprovalLevel"];
            items: components["schemas"]["ApprovalItem"][];
            history: components["schemas"]["ApprovalStep"][];
        };
        ApprovalPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["Approval"][];
        };
        ApprovalSummary: {
            pending: number;
            approved: number;
            rejected: number;
            pendingAmount: number;
            /** @description รายการรอที่ต้องให้เจ้าของอนุมัติ */
            ownerPending: number;
        };
        DecisionInput: {
            note?: string;
        };
        RejectInput: {
            note: string;
        };
        BulkApproveResult: {
            approved: components["schemas"]["Approval"][];
            skipped: {
                id: string;
                reason: string;
            }[];
        };
        /** @enum {string} */
        AuditModule: "approval" | "project" | "personnel" | "procurement" | "finance" | "system";
        AuditEntry: {
            id: string;
            /** Format: date-time */
            at: string;
            user: components["schemas"]["UserRef"];
            module: components["schemas"]["AuditModule"];
            /** @description ข้อความการกระทำ (ภาษาไทย) */
            action: string;
            /** @description เลขที่/รหัสของสิ่งที่ถูกกระทำ */
            target: string;
            detail?: string;
        };
        AuditLogPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["AuditEntry"][];
        };
        /** @enum {string} */
        ProjectHealth: "normal" | "behind" | "over-budget" | "loss";
        ProjectFinance: {
            projectCode: string;
            customerName: string;
            contractValue: number;
            progress: number;
            /** @description ความคืบหน้าที่ควรเป็นตามเวลา */
            plannedProgress: number;
            budgetCost: number;
            /** @description รายได้รับรู้ตามความคืบหน้า */
            earnedRevenue: number;
            actualCost: number;
            grossProfit: number;
            /** @description % ของรายได้รับรู้ */
            margin: number;
            /** @description กำไรที่คาดเมื่อจบโครงการ */
            forecastProfit: number;
            cashReceived: number;
            receivable: number;
            health: components["schemas"]["ProjectHealth"];
        };
        /**
         * @description pending-contract = รอทำสัญญา, active = กำลังดำเนินการ (มีสัญญาแล้ว ยังไม่ส่งมอบ),
         *     in-hand = โครงการในมือ (รอทำสัญญา + กำลังดำเนินการ), completed = ส่งมอบแล้ว,
         *     warranty = ส่งมอบแล้วและยังอยู่ในระยะประกัน
         * @enum {string}
         */
        ProjectGroup: "in-hand" | "pending-contract" | "active" | "completed" | "warranty";
        ProjectPortfolio: {
            /** Format: date-time */
            asOf: string;
            /** @description ระยะรับประกันผลงานหลังส่งมอบ (เดือน) */
            warrantyMonths: number;
            counts: {
                total: number;
                inHand: number;
                pendingContract: number;
                active: number;
                completed: number;
                warranty: number;
            };
            /** @description แยกโครงการที่กำลังดำเนินการตามสถานะ */
            activeByStatus: {
                planning: number;
                "in-progress": number;
                "near-handover": number;
                delayed: number;
            };
            /** @description มูลค่าสัญญาของโครงการที่กำลังดำเนินการ (เฉพาะสิทธิ์ finance.company) */
            inHandValue?: number;
            /** @description โครงการที่ยังอยู่ในประกัน เรียงตามวันหมดประกันที่ใกล้ที่สุด */
            warranties: {
                code: string;
                name: string;
                customerName: string;
                /** Format: date */
                handedOverAt: string;
                /** Format: date */
                warrantyUntil: string;
                daysLeft: number;
            }[];
        };
        DashboardSummary: {
            /** Format: date-time */
            asOf: string;
            totals: {
                contractValue: number;
                backlog: number;
                activeProjects: number;
                earnedRevenue: number;
                actualCost: number;
                grossProfit: number;
                margin: number;
                forecastProfit: number;
                cashReceived: number;
                receivable: number;
            };
            projects: components["schemas"]["ProjectFinance"][];
        };
        MonthlyCashFlow: {
            /**
             * @description YYYY-MM
             * @example 2026-10
             */
            month: string;
            cashIn: number;
            cashOut: number;
        };
    };
    responses: {
        /** @description ยังไม่ได้ล็อกอินหรือ token หมดอายุ */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description บทบาทนี้ไม่มีสิทธิ์ */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description ไม่พบข้อมูล */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description สถานะข้อมูลเปลี่ยนไปแล้ว เช่น คำขอถูกตัดสินไปก่อนหน้า */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description ข้อมูลไม่ถูกต้อง */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProjectCode: string;
        ApprovalId: string;
        /** @description เริ่มที่ 1 */
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ออกจากระบบแล้ว */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRef"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleCatalog"];
                };
            };
        };
    };
    getApprovalSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalSettings"];
                };
            };
        };
    };
    updateApprovalSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalSettings"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"];
                /** @description กลุ่มโครงการ (ดู ProjectGroup) */
                group?: components["schemas"]["ProjectGroup"];
                /** @description ค้นหารหัส ชื่อลูกค้า ผู้รับผิดชอบ */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description เปิดโครงการแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRegion"][];
                };
            };
        };
    };
    listConstructionOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructionOptionGroup"][];
                };
            };
        };
    };
    listHousePlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousePlan"][];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    recordProjectContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getProjectSetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSetup"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    saveProjectSetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSetupInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSetup"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    previewProjectSetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSetupInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupPreview"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getProjectTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectTimeline"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProgressUpdates: {
        parameters: {
            query?: {
                /** @description เริ่มที่ 1 */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressUpdatePage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createProgressUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdateInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressUpdate"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    recordInspection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                taskCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว (คืนรายการบันทึกหน้างานที่สร้างขึ้น) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressUpdate"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description ไม่เกิน 10 MB — รูป (JPG/PNG/WebP) หรือเอกสาร (PDF, Excel, Word, DWG) รูปหน้างาน (photoIds) ต้องเป็นรูปเท่านั้น
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description อัปโหลดแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadedFile"];
                };
            };
            413: components["responses"]["ValidationError"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectInstallments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Installment"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectPhotos: {
        parameters: {
            query?: {
                phaseCode?: string;
                /** @description เริ่มที่ 1 */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitePhotoPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectDocuments: {
        parameters: {
            query?: {
                category?: components["schemas"]["DocumentCategory"];
                q?: string;
            };
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAssignments"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    addProjectStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffAssignmentInput"];
            };
        };
        responses: {
            /** @description เพิ่มแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAssignment"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateProjectStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffAssignmentInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAssignment"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeProjectStaff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description นำออกแล้ว */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    addProjectSubcontractor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractorAssignmentInput"];
            };
        };
        responses: {
            /** @description มอบหมายแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubcontractorAssignment"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateProjectSubcontractor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractorAssignmentInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubcontractorAssignment"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeProjectSubcontractor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ยกเลิกแล้ว */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSubcontractors: {
        parameters: {
            query?: {
                /** @description ค้นหาชื่อ รหัส ผู้ติดต่อ */
                q?: string;
                trade?: components["schemas"]["SubcontractorTrade"];
                status?: "active" | "inactive";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcontractor"][];
                };
            };
        };
    };
    createSubcontractor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractorInput"];
            };
        };
        responses: {
            /** @description เพิ่มแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcontractor"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateSubcontractor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubcontractorInput"];
            };
        };
        responses: {
            /** @description บันทึกแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subcontractor"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["ProjectCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMember"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getHousePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousePlan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPersonnel: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Personnel"][];
                };
            };
        };
    };
    createPersonnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonnelInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Personnel"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getPersonnel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Personnel"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePersonnel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonnelInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Personnel"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listLicenseAlerts: {
        parameters: {
            query?: {
                withinDays?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenseAlert"][];
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
                type?: components["schemas"]["ApprovalType"];
                projectCode?: string;
                /** @description ค้นหาเลขที่ รายการ ผู้ขอ */
                q?: string;
                /** @description `priority` = รายการที่ต้องให้เจ้าของอนุมัติและยอดสูงก่อน */
                sort?: "newest" | "priority";
                /** @description เริ่มที่ 1 */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPage"];
                };
            };
        };
    };
    getApprovalSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalSummary"];
                };
            };
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    approveApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description อนุมัติแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApprovalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectInput"];
            };
        };
        responses: {
            /** @description ไม่อนุมัติแล้ว */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    bulkApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApproveResult"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                module?: components["schemas"]["AuditModule"];
                userId?: string;
                /** @description ค้นหาการกระทำ รายการ รายละเอียด */
                q?: string;
                from?: string;
                to?: string;
                /** @description เริ่มที่ 1 */
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    exportAuditLogs: {
        parameters: {
            query?: {
                module?: components["schemas"]["AuditModule"];
                userId?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ไฟล์ CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getProjectPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPortfolio"];
                };
            };
        };
    };
    getCashFlow: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyCashFlow"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
